---
title: "Data Cleaning"
author: "Anisha Dubhashi"
date: "11/11/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
```

###load all data from csv in working directory
```{r}
df <- read_csv("catalog sales data.csv")
```

###convert dates to date type
```{r}
df$datead6 <- as.Date(df$datead6,format = "%m/%d/%Y")
df$datelp6 <- as.Date(df$datelp6,format = "%m/%d/%Y")
```

### compare datelp6 to lpuryear - think lpuryear isn't necessary
```{r}
df2 <- df[df$targdol > 0, ]

table(df$lpuryear, format(df$datelp6, "%Y"), useNA = "ifany")
```

###~200 orders have no sales value for each year 
```{r}
#2012
table(df$slstyr > 0, df$ordtyr > 0, dnn = c("sales", "orders"))

#2011
table(df$slslyr > 0, df$ordlyr > 0, dnn = c("sales", "orders"))

#2010
table(df$sls2ago > 0, df$ord2ago > 0, dnn = c("sales", "orders"))

#2009
table(df$sls3ago > 0, df$ord3ago > 0, dnn = c("sales", "orders"))

#history
tab <- table(df$slshist > 0, df$ordhist > 0, dnn = c("sales", "orders"))
tab

#percent of discrepancy 
sum(tab[1,2])/sum(tab)
```

###lots of discrepancies between orders and date of last purchase
```{r}
#2012
table(format(df$datelp6, "%Y"), df$ordtyr > 0, useNA = "ifany", dnn = c("year last order", "2012 order"))

#2011
table(format(df$datelp6, "%Y"), df$ordlyr > 0, useNA = "ifany", dnn = c("year last order", "2011 order"))

#2010
table(format(df$datelp6, "%Y"), df$ord2ago > 0, useNA = "ifany", dnn = c("year last order", "2010 order"))

#2009
table(format(df$datelp6, "%Y"), df$ord3ago > 0, useNA = "ifany", dnn = c("year last order", "2009 order"))
```

###fall & spring order history
```{r}
ordhist_desc <- (df$falord + df$sprord) - df$ordhist
table(ordhist_desc, useNA = "ifany", dnn = c("falord + sprord - ordhist"))

#falord + sprord < ordhist
sum(ordhist_desc < 0)

#falord + sprord > ordhist
sum(ordhist_desc > 0)

#falord + sprord = ordhist
sum(ordhist_desc == 0)
```

###order history vs. orders each year
```{r}
ordhist_desc2 <- (df$ordtyr + df$ordlyr + df$ord2ago + df$ord3ago) - df$ordhist
table(ordhist_desc2, useNA = "ifany", dnn = c("ord - ordhist"))

#falord + sprord < ordhist
sum(ordhist_desc2 < 0)

#falord + sprord > ordhist
sum(ordhist_desc2 > 0)

#falord + sprord = ordhist
sum(ordhist_desc2 == 0)
```

```{r}


#create year_lp6yr
df$year_lp6yr <- format(df$datelp6, "%Y")
barplot(table(df$year_lp6yr))

#create year_lpuryr
df$year_lpuryr <- format(1980, format = "%Y")

for (i in 1:nrow(df)) {
  if (is.na(df$lpuryear[i])) {
    df$year_lpuryr[i] <- format(1980, format = "%Y")
  } else if (df$lpuryear[i] <= 2) {
    df$year_lpuryr[i] <- format(df$lpuryear[i] + 2010, format = "%Y")
  } else if (df$lpuryear[i] > 2) {
    df$year_lpuryr[i] <- format(df$lpuryear[i] + 2000, format = "%Y")
  }  
}
barplot(table(df$year_lpuryr))




#create year_ordyr
df$year_ordyr <- format(1980, format = "%Y")

for (i in 1:nrow(df)) {
  if (df$ordtyr[i] > 0) {
    df$year_ordyr[i] <- format(2012, format = "%Y")
  } else if (df$ordlyr[i] > 0) {
    df$year_ordyr[i] <- format(2011, format = "%Y")
  } else if (df$ord2ago[i] > 0) {
    df$year_ordyr[i] <- format(2010, format = "%Y")
  } else if (df$ord3ago[i] > 0) {
    df$year_ordyr[i] <- format(2009, format = "%Y")
  }  
}
barplot(table(df$year_ordyr))
```

```{r}
table(df$year_lp6yr, df$year_lpuryr)


df[, c('year_lp6yr', 'year_lpuryr', 'year_ordyr') ]

df %>% 
  group_by(year_lp6yr, year_lpuryr, year_ordyr) %>% 
  summarise(n = n())

```









