---
title: "11_27_logistic_Vincent"
author: "Ziwen Wang"
date: "11/27/2017"
output: pdf_document
---


```{r, include=FALSE}
#install.packages("tidyverse")
library(tidyverse)
library(lubridate)
```

###load all data from csv in working directory
```{r}
df <- read_csv("cleandata.csv")

#change the targdol to 0:1
df$targdol[df$targdol!=0]=1

#add lpmonth
df$lpmonth<-month(df$datelp6)
df$lpmonth<-as.integer(df$lpmonth)

#drop columns
df <- subset(df, select = -c(X1, consistencycategory, datead6, datelp6, lpuryear, ordhist, recency_year,  consistencycategory) )

head(df)
```

```{r}
#buy rate
sum(df$targdol)/nrow(df)
```


```{r}
#change season category to 0(fall) and 1(spring)
is.factor(df$recentseason)
df$recentseason<-as.character(df$recentseason)
df$recentseason[df$recentseason=='Spring']=0
df$recentseason[df$recentseason=='Fall']=1
df$recentseason<-as.factor(df$recentseason)
#contrasts(df$recentseason)

#correct the data type
df$targdol<-as.factor(df$targdol)
df$recentseason<-as.factor(df$recentseason)
```

```{r}
#split the train and test
train<-df[df$train==1,]
test<-df[df$train==0,]

train<-subset(train, select = -train)
test<-subset(test, select = -train)
```


```{r}
# #frequency tables/logistic transform plot (see pg 131 of book)
# frequency_table<- function(df,predictor, name) {
#   tab <- as.data.frame.matrix(table(predictor, df$targdol)) 
#   tab$buy_prop <- tab[,2]/rowSums(tab)
#   tab$log_odds <- log(tab$buy_prop/(1 - tab$buy_prop)) 
#   return (plot(x = as.numeric(rownames(tab)),
#                y = tab$log_odds, xlab = name,
#                ylab = 'log odds'))
# }
# 
# #plot
# par(mfrow = c(2, 2)) 
# frequency_table(train,year(train$datead6), 'datead6') 
# frequency_table(train,year(train$datelp6), 'datelp6') 
# frequency_table(train,train$lpuryear, 'lpuryear')
# 
# #frequency tables/logistic transform plot (see pg 131 of book)
# frequency_table2 <- function(df,predictor, name) {
#   tab <- as.data.frame.matrix(table(predictor, df$targdol)) 
#   tab$buy_prop <- tab[,2]/rowSums(tab)
#   tab$log_odds <- log(tab$buy_prop/(1 - tab$buy_prop)) 
#   return (plot(x = as.numeric(rownames(tab)),
#                y = tab$log_odds, xlab = name,
#                ylab = 'log odds',xlim=c(0,500)))
# }
# 
# par(mfrow = c(2, 3))
# frequency_table2(train,train$slstyr, 'slstyr') 
# frequency_table2(train,train$slslyr, 'slslyr') 
# frequency_table2(train,train$sls2ago, 'sls2ago') 
# frequency_table2(train,train$sls3ago, 'sls3ago') 
# frequency_table2(train,train$slshist, 'slshist')
# 
# #frequency_table2(train,(train$slshist)^0.5, 'slshist')
# #try to square the slshist
# 
# par(mfrow = c(2, 3))
# 
# frequency_table(train,train$ordtyr, 'ordtyr') 
# frequency_table(train,train$ordlyr, 'ordlyr') 
# frequency_table(train,train$ord2ago, 'ord2ago') 
# frequency_table(train,train$ord3ago, 'ord3ago') 
# frequency_table(train,train$ordhist, 'ordhist')
# 
# #we can try to use quadratic degree to ordtyr and ord2ago
# 
# par(mfrow = c(2, 2))
# 
# frequency_table(train,train$falord, 'falord')
# frequency_table(train,train$sprord, 'sprord') 
# frequency_table(train,train$years_since_purchase, 'years_since_purchase')
```



```{r}
#first_logistic_regression without interaction terms
# model1 <- glm(targdol ~.,family=binomial(link='logit'),data=train)
# summary(model1)
# anova(model1, test="Chisq")
```


```{r}
#trans_logistic_regression
train_2<-train
train_2$slshist_0.5<-(train_2$slshist)^0.5
train_2$ordtyr_2<-(train_2$ordtyr)^2
train_2$ord2ago_0.5<-(train_2$ord2ago)^0.5
train_2$sprord_0.5<-(train_2$sprord)^0.5
train_2$years_since_purchase_0.5<-(train_2$years_since_purchase)^0.5
```

```{r}
train_2$slstyr_slslyr <- train_2$slstyr*train_2$slslyr
train_2$slslyr_sls2ago <- train_2$slslyr*train_2$sls2ago
train_2$sls2ago_sls3ago <- train_2$sls2ago*train_2$sls3ago
train_2$slstyr_slslyr_sls2ago <- train_2$sls2ago*train_2$slstyr*train_2$slslyr
train_2$slstyr_slslyr_sls2ago_sls3ago <- train_2$sls3ago*train_2$sls2ago*train_2$slstyr*train_2$slslyr
train_2$slstyr_slslyr_sls2ago_sls3ago[is.na(train_2$slstyr_slslyr_sls2ago_sls3ago)] <- 0

train_2$slstyr_sls2ago <- train_2$slstyr*train_2$sls2ago
train_2$slstyr_sls3ago <- train_2$slstyr*train_2$sls3ago
train_2$slslyr_sls3ago <- train_2$slslyr*train_2$sls3ago
train_2$slslyr_sls2ago_sls3ago <- train_2$sls2ago*train_2$sls3ago*train_2$slslyr

train_2$slstyr_slshist <- train_2$slstyr*train_2$slshist
train_2$slslyr_slshist <- train_2$slslyr*train_2$slshist
train_2$sls2ago_slshist <- train_2$sls2ago*train_2$slshist
train_2$sls3ago_slshist <- train_2$sls3ago*train_2$slshist

train_2$slstyr_greater_slslyr <- (train_2$slstyr > train_2$slslyr)
train_2$slslyr_greater_sls2ago <- (train_2$slslyr > train_2$sls2ago)
train_2$sls2ago_greater_sls3ago <- (train_2$sls2ago > train_2$sls3ago)

```


```{r}
train_2$consistent1 <- as.numeric(train_2$ordtyr > 0
                               & train_2$ordlyr > 0
                               & train_2$ord2ago > 0
                               & train_2$ord3ago > 0)
train_2$consistent2 <- as.numeric(train_2$ordtyr == 0
                               & train_2$ordlyr > 0
                               & train_2$ord2ago > 0
                               & train_2$ord3ago > 0)
train_2$consistent3 <- as.numeric(train_2$ordtyr > 0
                               & train_2$ordlyr > 0
                               & train_2$ord2ago > 0
                               & train_2$ord3ago == 0)
train_2$consistent4 <- as.numeric(train_2$ordtyr > 0
                               & train_2$ordlyr > 0
                               & train_2$ord2ago == 0
                               & train_2$ord3ago > 0)
train_2$consistent5 <- as.numeric(train_2$ordtyr > 0
                               & train_2$ordlyr == 0
                               & train_2$ord2ago > 0
                               & train_2$ord3ago > 0)
train_2$consistent6 <- as.numeric(train_2$ordtyr > 0
                               & train_2$ordlyr > 0
                               & train_2$ord2ago == 0
                               & train_2$ord3ago == 0)
train_2$consistent7 <- as.numeric(train_2$ordtyr == 0
                               & train_2$ordlyr > 0
                               & train_2$ord2ago > 0
                               & train_2$ord3ago == 0)
train_2$consistent8 <- as.numeric(train_2$ordtyr == 0
                               & train_2$ordlyr == 0
                               & train_2$ord2ago > 0
                               & train_2$ord3ago > 0)
train_2$consistent9 <- as.numeric(train_2$ordtyr > 0
                               & train_2$ordlyr == 0
                               & train_2$ord2ago > 0
                               & train_2$ord3ago == 0)
train_2$consistent10 <- as.numeric(train_2$ordtyr == 0
                                & train_2$ordlyr > 0
                                & train_2$ord2ago == 0
                                & train_2$ord3ago > 0)
train_2$consistent11 <- as.numeric(train_2$ordtyr > 0
                                & train_2$ordlyr == 0
                                & train_2$ord2ago == 0
                                & train_2$ord3ago > 0)
```


```{r}
#full model
model.full <- glm(targdol ~ . ,family=binomial(link='logit'),data=train_2)
summary(model.full)
anova(model.full, test="Chisq")
```



```{r}
#stepwise
step(model.full,
     scope = list(upper=model.full),
             direction="both",
             test="Chisq",
             data=train_2)
```

```{r}
#HARDCODE
model.stepwise <- glm(formula = targdol ~ sls3ago + slshist + ordtyr + ordlyr + 
    falord + sprord + recentseason + years_since_purchase + lpmonth + 
    slshist_0.5 + ordtyr_2 + sprord_0.5 + years_since_purchase_0.5 + 
    slstyr_slslyr_sls2ago_sls3ago + slstyr_sls3ago + slstyr_slshist + 
    sls2ago_slshist + slstyr_greater_slslyr + consistent3 + consistent4 + 
    consistent7 + consistent9 + consistent10 + consistent11, 
    family = binomial(link = "logit"), data = train_2)
summary(model.stepwise)
```


```{r}
library(car)
vif(model.stepwise)
```

```{r}
# try to exclude multicolinear predictors - we decided not to since it causes partial model to be worse than the full model

model.final <- glm(formula = targdol ~ sls3ago + slshist + ordtyr + ordlyr + 
    falord + sprord + recentseason + years_since_purchase + lpmonth + 
    slshist_0.5 + ordtyr_2 + sprord_0.5 + years_since_purchase_0.5 + 
    slstyr_slslyr_sls2ago_sls3ago + slstyr_sls3ago + slstyr_slshist + 
    sls2ago_slshist + slstyr_greater_slslyr + consistent3 + consistent4 + 
    consistent7 + consistent9 + consistent10 + consistent11, 
    family = binomial(link = "logit"), data = train_2)
summary(model.final)
vif(model.final)

```

```{r}
anova(model.full, model.final,test="Chisq")
```





```{r}
#prediction
#first prediction
library(pscl)
# #pR2(model)
# test_predict <- predict(model.final, newdata = test, type = 'response') 
# table(test$targdol, round(test_predict, 1), dnn = c('true', 'predicted'))
# 
# test_predict[test_predict < .1] <- 0 
# test_predict[test_predict >= .1] <- 1
# tab <- table(test$targdol, test_predict, dnn = c('true', 'predicted')) 
# head(tab)
# cat('CCR:', sum(diag(tab))/sum(tab))
# cat('\nTrue targdol of predicted buyers', sum(as.integer(test$targdol[test_predict == 1])))

```

```{r}
#prediction
#optCutOff
#decide a optimal cutoff
#library(InformationValue)
# optCutOff <- optimalCutoff(test$targdol,test_predict)[1] 
# optCutOff
```

```{r}
#prediction
#second prediction - cutoff<- 0.01
# library(pscl)
# #pR2(model)
# test_predict <- predict(model.final, newdata = test, type = 'response') 
# table(test$targdol, round(test_predict, 1), dnn = c('true', 'predicted'))
# 
# test_predict[test_predict < .4] <- 0 
# test_predict[test_predict >= .4] <- 1
# tab <- table(test$targdol, test_predict, dnn = c('true', 'predicted')) 
# tab
# cat('CCR:', sum(diag(tab))/sum(tab))
# cat('\nTrue targdol of predicted buyers', sum(as.integer(test$targdol[test_predict == 1])))

```

```{r}
#change the targdol to 0:1
# test_logistic<-test
# test_logistic$targdol[test_logistic$targdol!=0]=1
```


```{r}
#fitted.results2 = predict(mod_fit, newdata=test_balanced)
# fitted.results <- predict(model.final,newdata=test_logistic,type='response')
# fitted.results <- ifelse(fitted.results > 0.4,1,0)
# misClasificError <- mean(fitted.results != test_logistic$targdol)
# print(paste('Accuracy',1-misClasificError))
```

```{r}
#ROC
# library(ROCR)
# p <- predict(model.final, newdata=test_logistic, type="response")
# 
# pr <- prediction(p, test_logistic$targdol)
# prf <- performance(pr, measure = "tpr", x.measure = "fpr")
# plot(prf)
# 
# auc <- performance(pr, measure = "auc")
# auc <- auc@y.values[[1]]
# auc
```








```{r}
##test logistic
test_logistic<-test

#add in extra variables to test
test_logistic<-train
test_logistic$slshist_0.5<-(test_logistic$slshist)^0.5
test_logistic$ordtyr_2<-(test_logistic$ordtyr)^2
test_logistic$ord2ago_0.5<-(test_logistic$ord2ago)^0.5
test_logistic$sprord_0.5<-(test_logistic$sprord)^0.5
test_logistic$years_since_purchase_0.5<-(test_logistic$years_since_purchase)^0.5


test_logistic$slstyr_slslyr <- test_logistic$slstyr*test_logistic$slslyr
test_logistic$slslyr_sls2ago <- test_logistic$slslyr*test_logistic$sls2ago
test_logistic$sls2ago_sls3ago <- test_logistic$sls2ago*test_logistic$sls3ago
test_logistic$slstyr_slslyr_sls2ago <- test_logistic$sls2ago*test_logistic$slstyr*test_logistic$slslyr
test_logistic$slstyr_slslyr_sls2ago_sls3ago <- test_logistic$sls3ago*test_logistic$sls2ago*test_logistic$slstyr*test_logistic$slslyr
test_logistic$slstyr_slslyr_sls2ago_sls3ago[is.na(test_logistic$slstyr_slslyr_sls2ago_sls3ago)] <- 0

test_logistic$slstyr_sls2ago <- test_logistic$slstyr*test_logistic$sls2ago
test_logistic$slstyr_sls3ago <- test_logistic$slstyr*test_logistic$sls3ago
test_logistic$slslyr_sls3ago <- test_logistic$slslyr*test_logistic$sls3ago
test_logistic$slslyr_sls2ago_sls3ago <- test_logistic$sls2ago*test_logistic$sls3ago*test_logistic$slslyr

test_logistic$slstyr_slshist <- test_logistic$slstyr*test_logistic$slshist
test_logistic$slslyr_slshist <- test_logistic$slslyr*test_logistic$slshist
test_logistic$sls2ago_slshist <- test_logistic$sls2ago*test_logistic$slshist
test_logistic$sls3ago_slshist <- test_logistic$sls3ago*test_logistic$slshist

test_logistic$slstyr_greater_slslyr <- (test_logistic$slstyr > test_logistic$slslyr)
test_logistic$slslyr_greater_sls2ago <- (test_logistic$slslyr > test_logistic$sls2ago)
test_logistic$sls2ago_greater_sls3ago <- (test_logistic$sls2ago > test_logistic$sls3ago)


test_logistic$consistent1 <- as.numeric(test_logistic$ordtyr > 0
                               & test_logistic$ordlyr > 0
                               & test_logistic$ord2ago > 0
                               & test_logistic$ord3ago > 0)
test_logistic$consistent2 <- as.numeric(test_logistic$ordtyr == 0
                               & test_logistic$ordlyr > 0
                               & test_logistic$ord2ago > 0
                               & test_logistic$ord3ago > 0)
test_logistic$consistent3 <- as.numeric(test_logistic$ordtyr > 0
                               & test_logistic$ordlyr > 0
                               & test_logistic$ord2ago > 0
                               & test_logistic$ord3ago == 0)
test_logistic$consistent4 <- as.numeric(test_logistic$ordtyr > 0
                               & test_logistic$ordlyr > 0
                               & test_logistic$ord2ago == 0
                               & test_logistic$ord3ago > 0)
test_logistic$consistent5 <- as.numeric(test_logistic$ordtyr > 0
                               & test_logistic$ordlyr == 0
                               & test_logistic$ord2ago > 0
                               & test_logistic$ord3ago > 0)
test_logistic$consistent6 <- as.numeric(test_logistic$ordtyr > 0
                               & test_logistic$ordlyr > 0
                               & test_logistic$ord2ago == 0
                               & test_logistic$ord3ago == 0)
test_logistic$consistent7 <- as.numeric(test_logistic$ordtyr == 0
                               & test_logistic$ordlyr > 0
                               & test_logistic$ord2ago > 0
                               & test_logistic$ord3ago == 0)
test_logistic$consistent8 <- as.numeric(test_logistic$ordtyr == 0
                               & test_logistic$ordlyr == 0
                               & test_logistic$ord2ago > 0
                               & test_logistic$ord3ago > 0)
test_logistic$consistent9 <- as.numeric(test_logistic$ordtyr > 0
                               & test_logistic$ordlyr == 0
                               & test_logistic$ord2ago > 0
                               & test_logistic$ord3ago == 0)
test_logistic$consistent10 <- as.numeric(test_logistic$ordtyr == 0
                                & test_logistic$ordlyr > 0
                                & test_logistic$ord2ago == 0
                                & test_logistic$ord3ago > 0)
test_logistic$consistent11 <- as.numeric(test_logistic$ordtyr > 0
                                & test_logistic$ordlyr == 0
                                & test_logistic$ord2ago == 0
                                & test_logistic$ord3ago > 0)
```


```{r}
library(ROCR)
p.full <- predict(model.full, newdata=test_logistic, type="response")
plotROC(test_logistic$targdol, p.full)

p.final <- predict(model.final, newdata=test_logistic, type="response")
plotROC(test_logistic$targdol, p.final)
```

```{r}
# #
# pr <- prediction(p, test_logistic$targdol)
# test_logistic$targdol<-as.factor(test_logistic$targdol)
# #p<-as.factor(p)
# sensitivity(test_logistic$targdol, p, threshold = 0.4)
# specificity(test_logistic$targdol, p, threshold = 0.4)
# confusionMatrix(test_logistic$targdol, p, threshold = 0.4)
# # The columns are actuals, while rows are predicteds.
# 
# # Use your model to make predictions, in this example newdata = training set, but replace with your test set    
# 
# # use caret and compute a confusion matrix
# confusionMatrix(test_logistic$targdol, p, threshold = 0.4)
```
