---
title: "Untitled"
author: "Zili Li"
date: "November 29, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
```

###load all data from csv in working directory
```{r}
catalogdataclean <- read.csv("cleandata.csv")
```

###convert dates to date type
```{r}
catalogdataclean$datead6 <- as.Date(catalogdataclean$datead6,format = "%m/%d/%Y")
catalogdataclean$datelp6 <- as.Date(catalogdataclean$datelp6,format = "%m/%d/%Y")
```

```{r}
test <- catalogdataclean[catalogdataclean$train == 0,]
```

```{r}
salestest <- test[test$targdol > 0,]
```

```{r}
salestest$consistencycategory <- as.factor(salestest$consistencycategory)
```

```{r}
salestest$recentseason<-as.character(salestest$recentseason)
salestest$recentseason[salestest$recentseason=='Spring']=0
salestest$recentseason[salestest$recentseason=='Fall']=1
salestest$recentseason<-as.factor(salestest$recentseason)
```

```{r}
salestest$consistencycategory <- as.factor(salestest$consistencycategory)
salestest$consistencycategory <- relevel(salestest$consistencycategory,"Ref")
```



```{r}
colnames(salestest)
relevantvarnames <- c("targdol","slstyr","slslyr","sls2ago","sls3ago","slshist","ordtyr","ordlyr","ord2ago","ord3ago","ordhist","falord","sprord","recentseason","years_since_purchase","consistencycategory")
test.vars <- salestest[,(names(salestest) %in% relevantvarnames)]
```

```{r}
test.vars$slstyr_slslyr <- test.vars$slstyr*test.vars$slslyr
test.vars$slslyr_sls2ago <- test.vars$slslyr*test.vars$sls2ago
test.vars$sls2ago_sls3ago <- test.vars$sls2ago*test.vars$sls3ago
test.vars$slstyr_slslyr_sls2ago <- test.vars$sls2ago*test.vars$slstyr*test.vars$slslyr
test.vars$slstyr_slslyr_sls2ago_sls3ago <- test.vars$sls3ago*test.vars$sls2ago*test.vars$slstyr*test.vars$slslyr
test.vars$slstyr_slslyr_sls2ago_sls3ago[is.na(test.vars$slstyr_slslyr_sls2ago_sls3ago)] <- 0

test.vars$slstyr_sls2ago <- test.vars$slstyr*test.vars$sls2ago
test.vars$slstyr_sls3ago <- test.vars$slstyr*test.vars$sls3ago
test.vars$slslyr_sls3ago <- test.vars$slslyr*test.vars$sls3ago
test.vars$slslyr_sls2ago_sls3ago <- test.vars$sls2ago*test.vars$sls3ago*test.vars$slslyr

test.vars$slstyr_slshist <- test.vars$slstyr*test.vars$slshist
test.vars$slslyr_slshist <- test.vars$slslyr*test.vars$slshist
test.vars$sls2ago_slshist <- test.vars$sls2ago*test.vars$slshist
test.vars$sls3ago_slshist <- test.vars$sls3ago*test.vars$slshist

test.vars$slstyr_greater_slslyr <- (test.vars$slstyr > test.vars$slslyr)
test.vars$slslyr_greater_sls2ago <- (test.vars$slslyr > test.vars$sls2ago)
test.vars$sls2ago_greater_sls3ago <- (test.vars$sls2ago > test.vars$sls3ago)

```


```{r}
library(dummies)
test.vars <- cbind(test.vars,dummy(test.vars$consistencycategory))
colnames(test.vars)
test.vars <- within(test.vars,rm("consistencycategory"))
test.vars <- within(test.vars,rm("test.varsRef"))

test.vars <- within(test.vars,rm("sprord"))

names(test.vars)[names(test.vars) == 'test.vars1'] <- 'consistent1'
names(test.vars)[names(test.vars) == 'test.vars2'] <- 'consistent2'
names(test.vars)[names(test.vars) == 'test.vars3'] <- 'consistent3'
names(test.vars)[names(test.vars) == 'test.vars4'] <- 'consistent4'
names(test.vars)[names(test.vars) == 'test.vars5'] <- 'consistent5'
names(test.vars)[names(test.vars) == 'test.vars6'] <- 'consistent6'
names(test.vars)[names(test.vars) == 'test.vars7'] <- 'consistent7'
names(test.vars)[names(test.vars) == 'test.vars8'] <- 'consistent8'
names(test.vars)[names(test.vars) == 'test.vars9'] <- 'consistent9'
names(test.vars)[names(test.vars) == 'test.vars10'] <- 'consistent10'
names(test.vars)[names(test.vars) == 'test.vars11'] <- 'consistent11'

colnames(test.vars)
colnames(relevantvars2)
```




# log transformation
```{r}
var.log <- c('slstyr', "slslyr", "sls2ago", "sls3ago", "slshist",
    "ordtyr", "ordlyr", "ord2ago", "ord3ago","recentseason", "years_since_purchase",
    "slslyr_sls2ago", "slstyr_slslyr_sls2ago","slstyr_sls2ago",
    "slstyr_slshist","slslyr_slshist", "sls3ago_slshist","consistent1",
    "consistent2", "consistent3", "consistent5", "consistent7","consistent9")
test.log <- test.vars[,(names(test.vars) %in% var.log)]

colnames(test.log)
View(test.log)

dol.predict <- predict(fit.step.rm, newdata = test.log)
```


```{r}
View(test.vars)

sum((test.vars$targdol-exp(dol.predict))^2)/(4726-26)
```


# sqrt transformation
```{r}
var.sqrt <- c("slstyr","slslyr","sls2ago","sls3ago","slshist","ordtyr","ordlyr","ord2ago","ord3ago","recentseason","years_since_purchase","slstyr_slslyr","slslyr_sls2ago", "sls2ago_sls3ago", "slstyr_slslyr_sls2ago", "slstyr_sls2ago","slstyr_slshist", "slslyr_slshist","sls2ago_slshist","consistent1","consistent3","consistent5","consistent9")


test.sqrt <- test.vars[,(names(test.vars) %in% var.sqrt)]

names(coef(fit.step.sqrt.rm))
colnames(test.sqrt)
dol.predict.sqrt <- predict(fit.step.sqrt.rm, newdata = test.sqrt)


sum((test.vars$targdol-(dol.predict.sqrt)^2)^2)/(4726-24)
```


# no transformation
```{r}
names(coef(fit.step.nolog))
var.nolog<- c("slstyr", "slslyr","sls2ago","sls3ago","slshist","ordtyr", "ordlyr","ord2ago","ord3ago","recentseason","slstyr_slslyr","slslyr_sls2ago","sls2ago_sls3ago","slstyr_slslyr_sls2ago","slstyr_sls2ago","slstyr_sls3ago","slstyr_slshist","slslyr_slshist","sls2ago_slshist", "slstyr_greater_slslyr",  "slslyr_greater_sls2ago", "consistent1","consistent3", "consistent5","consistent9")

test.nolog <- test.vars[,(names(test.vars) %in% var.nolog)]
colnames(test.nolog)

dol.predict.nolog <- predict(fit.step.nolog, newdata = test.nolog)

sum((test.vars$targdol-dol.predict.nolog)^2)/(4726-26)


# without outliers
dol.predict.nolog.rm <- predict(fit.step.nolog.rm, newdata = test.nolog)
sum((test.vars$targdol-dol.predict.nolog.rm)^2)/(4726-26)

# remove 1 outlier
dol.predict.nolog.rm1 <- predict(fit.step.nolog.rm1, newdata = test.nolog)
sum((test.vars$targdol-dol.predict.nolog.rm1)^2)/(4726-26)

```


# no interaction
```{r}
var.nointer <- c("slstyr","slslyr","sls2ago", "slshist", "ordlyr", "ord3ago", 
    "recentseason", "years_since_purchase","consistent1","consistent2",
    "consistent3","consistent5","consistent7","consistent9")
test.nointer <- test.vars[,(names(test.vars) %in% var.nointer)]
colnames(test.nointer)

dol.predict.nointer <- predict(fit.step.nointeraction, newdata = test.nointer)

sum((test.vars$targdol-dol.predict.nointer)^2)/(4726-15)


```

