---
title: "Untitled"
author: "Zili Li"
date: "November 20, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

###load all data from csv in working directory
```{r}
catalogdataclean <- read.csv("cleandata.csv")
```

###convert dates to date type
```{r}
catalogdataclean$datead6 <- as.Date(catalogdataclean$datead6,format = "%m/%d/%Y")
catalogdataclean$datelp6 <- as.Date(catalogdataclean$datelp6,format = "%m/%d/%Y")
```

```{r}
train <- catalogdataclean[catalogdataclean$train==1,]
```

```{r}
library(car)
```

```{r}
salestrain <- train[train$targdol > 0,]
```

```{r}
salestrain$recentseason<-as.character(salestrain$recentseason)
salestrain$recentseason[salestrain$recentseason=='Spring']=0
salestrain$recentseason[salestrain$recentseason=='Fall']=1
salestrain$recentseason<-as.factor(salestrain$recentseason)
```

```{r}
salestrain$consistencycategory <- as.factor(salestrain$consistencycategory)
```

```{r}
salestrain$consistencycategory <- relevel(salestrain$consistencycategory,"Ref")
```




```{r}
colnames(salestrain)
relevantvarnames <- c("targdol","slstyr","slslyr","sls2ago","sls3ago","slshist","ordtyr","ordlyr","ord2ago","ord3ago","ordhist","falord","sprord","recentseason","years_since_purchase","consistencycategory")
relevantvars <- salestrain[,(names(salestrain) %in% relevantvarnames)]
```


```{r}
head(relevantvars)
fit.nolog = lm(targdol~., data = relevantvars) 
summary(fit.nolog)
plot(fit.nolog, which = 2)
```

```{r}
fit = lm(log(targdol)~slstyr + slslyr + sls2ago + sls3ago + slshist + ordtyr + ordlyr + ord2ago + ord3ago + ordhist + falord + recentseason + years_since_purchase + consistencycategory,data = relevantvars)
summary(fit)
plot(fit, which = 2)

```

```{r}
par(mfrow = c(4, 4))

avPlot(fit,"slstyr")
avPlot(fit,"slslyr")
avPlot(fit,"sls2ago")
avPlot(fit,"sls3ago")
avPlot(fit,"slshist")
avPlot(fit,"ordtyr")
avPlot(fit,"ordlyr")
avPlot(fit,"ord2ago")
avPlot(fit,"ord3ago")
avPlot(fit,"ordhist")
avPlot(fit,"falord")
avPlot(fit,"recentseason1")
avPlot(fit,"years_since_purchase")
```


# Add more interaction terms
```{r}
relevantvars2 <- relevantvars
relevantvars2$slstyr_slslyr <- relevantvars2$slstyr*relevantvars2$slslyr
relevantvars2$slslyr_sls2ago <- relevantvars2$slslyr*relevantvars2$sls2ago
relevantvars2$sls2ago_sls3ago <- relevantvars2$sls2ago*relevantvars2$sls3ago
relevantvars2$slstyr_slslyr_sls2ago <- relevantvars2$sls2ago*relevantvars2$slstyr*relevantvars2$slslyr
relevantvars2$slstyr_slslyr_sls2ago_sls3ago <- relevantvars2$sls3ago*relevantvars2$sls2ago*relevantvars2$slstyr*relevantvars2$slslyr
relevantvars2$slstyr_slslyr_sls2ago_sls3ago[is.na(relevantvars2$slstyr_slslyr_sls2ago_sls3ago)] <- 0

relevantvars2$slstyr_sls2ago <- relevantvars2$slstyr*relevantvars2$sls2ago
relevantvars2$slstyr_sls3ago <- relevantvars2$slstyr*relevantvars2$sls3ago
relevantvars2$slslyr_sls3ago <- relevantvars2$slslyr*relevantvars2$sls3ago
relevantvars2$slslyr_sls2ago_sls3ago <- relevantvars2$sls2ago*relevantvars2$sls3ago*relevantvars2$slslyr

relevantvars2$slstyr_slshist <- relevantvars2$slstyr*relevantvars2$slshist
relevantvars2$slslyr_slshist <- relevantvars2$slslyr*relevantvars2$slshist
relevantvars2$sls2ago_slshist <- relevantvars2$sls2ago*relevantvars2$slshist
relevantvars2$sls3ago_slshist <- relevantvars2$sls3ago*relevantvars2$slshist

relevantvars2$slstyr_greater_slslyr <- (relevantvars2$slstyr > relevantvars2$slslyr)
relevantvars2$slslyr_greater_sls2ago <- (relevantvars2$slslyr > relevantvars2$sls2ago)
relevantvars2$sls2ago_greater_sls3ago <- (relevantvars2$sls2ago > relevantvars2$sls3ago)


```

```{r}
library(dummies)
relevantvars2 <- cbind(relevantvars2,dummy(relevantvars2$consistencycategory))
colnames(relevantvars2)
relevantvars2 <- within(relevantvars2,rm("consistencycategory"))
relevantvars2 <- within(relevantvars2,rm("relevantvars2Ref"))

relevantvars2 <- within(relevantvars2,rm("sprord"))

```

```{r}
names(relevantvars2)[names(relevantvars2) == 'relevantvars21'] <- 'consistent1'
names(relevantvars2)[names(relevantvars2) == 'relevantvars22'] <- 'consistent2'
names(relevantvars2)[names(relevantvars2) == 'relevantvars23'] <- 'consistent3'
names(relevantvars2)[names(relevantvars2) == 'relevantvars24'] <- 'consistent4'
names(relevantvars2)[names(relevantvars2) == 'relevantvars25'] <- 'consistent5'
names(relevantvars2)[names(relevantvars2) == 'relevantvars26'] <- 'consistent6'
names(relevantvars2)[names(relevantvars2) == 'relevantvars27'] <- 'consistent7'
names(relevantvars2)[names(relevantvars2) == 'relevantvars28'] <- 'consistent8'
names(relevantvars2)[names(relevantvars2) == 'relevantvars29'] <- 'consistent9'
names(relevantvars2)[names(relevantvars2) == 'relevantvars210'] <- 'consistent10'
names(relevantvars2)[names(relevantvars2) == 'relevantvars211'] <- 'consistent11'


colnames(relevantvars2)
```



```{r}
head(relevantvars2)
fit3 = lm(log(targdol)~.,data = relevantvars2)
summary(fit3)
```

# no transformation
```{r}
fit3.nolog = lm(targdol~.,data = relevantvars2)
summary(fit3.nolog)
```

# square-root transformation
```{r}
fit3.sqrt = lm(sqrt(targdol)~.,data = relevantvars2)
summary(fit3.sqrt)
```

# no interaction
```{r}
seq(15,30)
var.nointeraction <- relevantvars2[,-c(seq(15,30))]
colnames(var.nointeraction)
fit.nointeraction <- lm(targdol~., data=var.nointeraction)
step.nointeraction <- step(fit.nointeraction, direction = "backward")

fit.step.nointeraction <- lm(targdol ~ slstyr + slslyr + sls2ago + slshist + ordlyr + ord3ago + 
    recentseason + years_since_purchase + consistent1 + consistent2 + 
    consistent3 + consistent5 + consistent7 + consistent9, data = var.nointeraction)
summary(fit.step.nointeraction)

vif(fit.step.nointeraction)


```



# log stepwise
```{r}
step.forward <- step(fit3, direction = "forward")
step.back <- step(fit3, direction = "backward")
step.coef <- names(coef(step.back))
#step.var <- relevantvars2[,(names(relevantvars2) %in% c("targdol",step.coef))]

fit.step <- lm(log(targdol) ~ slstyr + slslyr + sls2ago + sls3ago + slshist + 
    ordtyr + ordlyr + ord2ago + ord3ago + recentseason + years_since_purchase + 
    slslyr_sls2ago + slstyr_slslyr_sls2ago + slstyr_sls2ago + 
    slstyr_slshist + slslyr_slshist + sls3ago_slshist + consistent1 + 
    consistent2 + consistent3 + consistent5 + consistent7 + consistent9, data = relevantvars2)
summary(fit.step)
```

# sqrt 
```{r}
step.back.sqrt <- step(fit3.sqrt, direction = "backward")
step.coef.sqrt <- names(coef(step.back.sqrt))
#step.var.sqrt <- relevantvars2[,(names(relevantvars2) %in% c("targdol",step.coef.sqrt))]
fit.step.sqrt <- lm(sqrt(targdol) ~ slstyr + slslyr + sls2ago + sls3ago + slshist + 
    ordtyr + ordlyr + ord2ago + ord3ago + recentseason + years_since_purchase + 
    slstyr_slslyr + slslyr_sls2ago + sls2ago_sls3ago + slstyr_slslyr_sls2ago + 
    slstyr_sls2ago + slstyr_slshist + slslyr_slshist + sls2ago_slshist + 
    consistent1 + consistent3 + consistent5 + consistent9, data = relevantvars2)
summary(fit.step.sqrt)



plot(fit.step.sqrt, which = 2)
plot(fit.step.sqrt, which = 1)
plot(fit.step.sqrt, which = 4)


```

```{r}
sqrt.rm <- c("48690","72035","38551")
```




# no transformation
```{r}
step.back.nolog <- step(fit3.nolog, direction = "backward")
step.coef.nolog <- names(coef(step.back.nolog))
step.coef.nolog
#step.var.nolog <- relevantvars2[,(names(relevantvars2) %in% c("targdol",step.coef.nolog,"recentseason","slstyr_greater_slslyr","slslyr_greater_sls2ago"))]
fit.step.nolog <- lm(targdol ~ slstyr + slslyr + sls2ago + sls3ago + slshist + ordtyr + 
    ordlyr + ord2ago + ord3ago + recentseason + slstyr_slslyr + 
    slslyr_sls2ago + sls2ago_sls3ago + slstyr_slslyr_sls2ago + 
    slstyr_sls2ago + slstyr_sls3ago + slstyr_slshist + slslyr_slshist + 
    sls2ago_slshist + slstyr_greater_slslyr + slslyr_greater_sls2ago + 
    consistent1 + consistent3 + consistent5 + consistent9, data = relevantvars2)
summary(fit.step.nolog)


plot(fit.step.nolog, which = 2)
plot(fit.step.nolog, which = 1)
plot(fit.step.nolog, which = 4)
```

```{r}
library(glmnet)
y = log(relevantvars2$targdol)
x.var <- relevantvars2[2:length(relevantvars2)]
x = model.matrix(~.-1,x.var)

lassofit = glmnet(x,y, alpha = 1, lambda = seq(0,10,0.01))
lassocv = cv.glmnet(x,y,alpha = 1, nfold = 3,lambda = seq(0,10,0.01))
plot(lassocv)
lambdalasso = lassocv$lambda.min
lambdalasso
small.lambda.index <- which(lassocv$lambda == lassocv$lambda.min)
small.lambda.betas <- coef(lassocv$glmnet.fit)[,small.lambda.index]
lasso.coef <- small.lambda.betas[small.lambda.betas != 0]
lasso.coef
```
```{r}
names(lasso.coef)
lasso.var <- relevantvars2[,(names(relevantvars2) %in% c("targdol",names(lasso.coef)[-1]))]
fit.lasso <- lm(log(targdol)~., data = lasso.var)
summary(fit.lasso)

```


## Model Diagnostics
```{r}
plot(fit.step, which = 2)
plot(fit.step, which = 1)
plot(fit.step, which = 4)
outlier <- cooks.distance(fit.step)[cooks.distance(fit.step) > 4/(4845-23)]


plot(fit.lasso, which = 2)
plot(fit.lasso, which = 1)
plot(fit.lasso, which = 4)
vif(fit.lasso)




vif(fit.step)
```

# remove outliers log
```{r}
rm <- c("48690","72035","72673")
step.var.rm <- relevantvars2[!rownames(relevantvars2) %in% rm,]


fit.step.rm <- lm(log(targdol) ~ slstyr + slslyr + sls2ago + sls3ago + slshist + 
    ordtyr + ordlyr + ord2ago + ord3ago + recentseason + years_since_purchase + 
    slslyr_sls2ago + slstyr_slslyr_sls2ago + slstyr_sls2ago + 
    slstyr_slshist + slslyr_slshist + sls3ago_slshist + consistent1 + 
    consistent2 + consistent3 + consistent5 + consistent7 + consistent9, data = step.var.rm)
summary(fit.step.rm)


# std residual
log.std <- rstandard(fit.step)
sort(log.std, decreasing = T)[1:3]
log.rm.std <- c("41618","12517","37929")
step.log.rm.std <- relevantvars2[!rownames(relevantvars2) %in% log.rm.std,]

fit.step.rm.std <- lm(log(targdol) ~ slstyr + slslyr + sls2ago + sls3ago + slshist + 
    ordtyr + ordlyr + ord2ago + ord3ago + recentseason + years_since_purchase + 
    slslyr_sls2ago + slstyr_slslyr_sls2ago + slstyr_sls2ago + 
    slstyr_slshist + slslyr_slshist + sls3ago_slshist + consistent1 + 
    consistent2 + consistent3 + consistent5 + consistent7 + consistent9, data = step.log.rm.std)
summary(fit.step.rm.std)


# remove both
step.log.rm.both <- step.var.rm[!rownames(step.var.rm) %in% log.rm.std,]
fit.step.rm.both <- lm(log(targdol) ~ slstyr + slslyr + sls2ago + sls3ago + slshist + 
    ordtyr + ordlyr + ord2ago + ord3ago + recentseason + years_since_purchase + 
    slslyr_sls2ago + slstyr_slslyr_sls2ago + slstyr_sls2ago + 
    slstyr_slshist + slslyr_slshist + sls3ago_slshist + consistent1 + 
    consistent2 + consistent3 + consistent5 + consistent7 + consistent9, data = step.log.rm.both)
summary(fit.step.rm.both)



plot(fit.step.rm, which = 2)
plot(fit.step.rm, which = 1)
plot(fit.step.rm, which = 4)

```


# sqrt outliers
```{r}
plot(fit.step.sqrt, which = 2)
plot(fit.step.sqrt, which = 1)
plot(fit.step.sqrt, which = 4)

fit.step.sqrt
sqrt.rm <- c("48690","72035","38551")
step.sqrt.rm <- relevantvars2[!rownames(relevantvars2) %in% sqrt.rm,]
fit.step.sqrt.rm <- lm(sqrt(targdol) ~ slstyr + slslyr + sls2ago + sls3ago + slshist + 
    ordtyr + ordlyr + ord2ago + ord3ago + recentseason + years_since_purchase + 
    slstyr_slslyr + slslyr_sls2ago + sls2ago_sls3ago + slstyr_slslyr_sls2ago + 
    slstyr_sls2ago + slstyr_slshist + slslyr_slshist + sls2ago_slshist + 
    consistent1 + consistent3 + consistent5 + consistent9, data = step.sqrt.rm)
summary(fit.step.sqrt.rm)

# std residual
sqrt.std <- rstandard(fit.step.sqrt)
sort(sqrt.std, decreasing = T)[1:3]
sqrt.rm.std <- c("41618","12517","37929")
step.sqrt.rm.std <- relevantvars2[!rownames(relevantvars2) %in% sqrt.rm.std,]

fit.step.sqrt.rm.std <- lm(sqrt(targdol) ~ slstyr + slslyr + sls2ago + sls3ago + slshist + 
    ordtyr + ordlyr + ord2ago + ord3ago + recentseason + years_since_purchase + 
    slstyr_slslyr + slslyr_sls2ago + sls2ago_sls3ago + slstyr_slslyr_sls2ago + 
    slstyr_sls2ago + slstyr_slshist + slslyr_slshist + sls2ago_slshist + 
    consistent1 + consistent3 + consistent5 + consistent9, data = step.sqrt.rm.std)

summary(fit.step.sqrt.rm.std)


# remove both
step.sqrt.rm.both <- step.sqrt.rm.std[!rownames(step.sqrt.rm.std) %in% sqrt.rm,]
fit.step.sqrt.rm.both <- lm(sqrt(targdol) ~ slstyr + slslyr + sls2ago + sls3ago + slshist + 
    ordtyr + ordlyr + ord2ago + ord3ago + recentseason + years_since_purchase + 
    slstyr_slslyr + slslyr_sls2ago + sls2ago_sls3ago + slstyr_slslyr_sls2ago + 
    slstyr_sls2ago + slstyr_slshist + slslyr_slshist + sls2ago_slshist + 
    consistent1 + consistent3 + consistent5 + consistent9, data = step.sqrt.rm.both)

summary(fit.step.sqrt.rm.both)
summary(fit.step.sqrt.rm.std)
summary(fit.step.sqrt.rm)
summary(fit.step.sqrt)
```


# no transformation outliers
```{r}
plot(fit.step.nolog, which = 2)
plot(fit.step.nolog, which = 1)
plot(fit.step.nolog, which = 4)

nolog.rm <- c("48690","72035","100006")
step.nolog.rm <- relevantvars2[!rownames(relevantvars2) %in% nolog.rm,]
fit.step.nolog.rm <- lm(targdol ~ slstyr + slslyr + sls2ago + sls3ago + slshist + ordtyr + 
    ordlyr + ord2ago + ord3ago + recentseason + slstyr_slslyr + 
    slslyr_sls2ago + sls2ago_sls3ago + slstyr_slslyr_sls2ago + 
    slstyr_sls2ago + slstyr_sls3ago + slstyr_slshist + slslyr_slshist + 
    sls2ago_slshist + slstyr_greater_slslyr + slslyr_greater_sls2ago + 
    consistent1 + consistent3 + consistent5 + consistent9, data = step.nolog.rm)
summary(fit.step.nolog.rm)
summary(fit.step.nolog)


step.nolog.rm1 <- relevantvars2[!rownames(relevantvars2) %in% c("48690"),]
fit.step.nolog.rm1 <- lm(targdol ~ slstyr + slslyr + sls2ago + sls3ago + slshist + ordtyr + 
    ordlyr + ord2ago + ord3ago + recentseason + slstyr_slslyr + 
    slslyr_sls2ago + sls2ago_sls3ago + slstyr_slslyr_sls2ago + 
    slstyr_sls2ago + slstyr_sls3ago + slstyr_slshist + slslyr_slshist + 
    sls2ago_slshist + slstyr_greater_slslyr + slslyr_greater_sls2ago + 
    consistent1 + consistent3 + consistent5 + consistent9, data = step.nolog.rm1)
summary(fit.step.nolog.rm1)

# Standardlized residual
nolog.stres<- rstandard(fit.step.nolog)
sort(nolog.stres, decreasing = T)[1:3]

nolog.rm.std <- c("41618","12517","11788")
step.nolog.rm.std <- relevantvars2[!rownames(relevantvars2) %in% nolog.rm.std,]
fit.step.nolog.rm.std <- lm(targdol ~ slstyr + slslyr + sls2ago + sls3ago + slshist + ordtyr + 
    ordlyr + ord2ago + ord3ago + recentseason + slstyr_slslyr + 
    slslyr_sls2ago + sls2ago_sls3ago + slstyr_slslyr_sls2ago + 
    slstyr_sls2ago + slstyr_sls3ago + slstyr_slshist + slslyr_slshist + 
    sls2ago_slshist + slstyr_greater_slslyr + slslyr_greater_sls2ago + 
    consistent1 + consistent3 + consistent5 + consistent9, data = step.nolog.rm.std)
summary(fit.step.nolog.rm.std)


vif(fit.step.nolog)

```



## Final Models
```{r}
# log-transformed
fit.step.rm.both

# sqrt-transformed
fit.step.sqrt.rm.both

# no transformation
fit.step.nolog

# no transformation and remove 3 outliers
fit.step.nolog.rm.std

```


