---
title: "Untitled"
author: "Zili Li"
date: "November 20, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

###load all data from csv in working directory
```{r}
catalogdataclean <- read.csv("cleandata.csv")
```

###convert dates to date type
```{r}
catalogdataclean$datead6 <- as.Date(catalogdataclean$datead6,format = "%m/%d/%Y")
catalogdataclean$datelp6 <- as.Date(catalogdataclean$datelp6,format = "%m/%d/%Y")
```

```{r}
train <- catalogdataclean[catalogdataclean$train==1,]
```

```{r}
library(car)
```

```{r}
salestrain <- train[train$targdol > 0,]
```

```{r}
salestrain$consistencycategory <- as.factor(salestrain$consistencycategory)
```

```{r}
salestrain$recentseason <- as.factor(salestrain$recentseason)
```

```{r}
salestrain$consistencycategory <- relevel(salestrain$consistencycategory,"Ref")
```

```{r}
salestrain$recentseason <- relevel(salestrain$recentseason,"Spring")
```


```{r}
colnames(salestrain)
relevantvarnames <- c("targdol","slstyr","slslyr","sls2ago","sls3ago","slshist","ordtyr","ordlyr","ord2ago","ord3ago","ordhist","falord","sprord","recentseason","years_since_purchase","consistencycategory")
relevantvars <- salestrain[,(names(salestrain) %in% relevantvarnames)]
```


```{r}
head(relevantvars)
fit.nolog = lm(targdol~., data = relevantvars) 
summary(fit.nolog)
plot(fit.nolog, which = 2)
```

```{r}
fit = lm(log(targdol)~slstyr + slslyr + sls2ago + sls3ago + slshist + ordtyr + ordlyr + ord2ago + ord3ago + ordhist + falord + recentseason + years_since_purchase + consistencycategory,data = relevantvars)
summary(fit)
plot(fit, which = 2)

```

```{r}
avPlot(fit,"slstyr")
avPlot(fit,"slslyr")
avPlot(fit,"sls2ago")
avPlot(fit,"sls3ago")
avPlot(fit,"slshist")
avPlot(fit,"ordtyr")
avPlot(fit,"ordlyr")
avPlot(fit,"ord2ago")
avPlot(fit,"ord3ago")
avPlot(fit,"ordhist")
avPlot(fit,"falord")
avPlot(fit,"recentseasonFall")
avPlot(fit,"years_since_purchase")
```


# Add more interaction terms
```{r}
relevantvars2 <- relevantvars
relevantvars2$slstyr_slslyr <- relevantvars2$slstyr*relevantvars2$slslyr
relevantvars2$slslyr_sls2ago <- relevantvars2$slslyr*relevantvars2$sls2ago
relevantvars2$sls2ago_sls3ago <- relevantvars2$sls2ago*relevantvars2$sls3ago
relevantvars2$slstyr_slslyr_sls2ago <- relevantvars2$sls2ago*relevantvars2$slstyr*relevantvars2$slslyr
relevantvars2$slstyr_slslyr_sls2ago_sls3ago <- relevantvars2$sls3ago*relevantvars2$sls2ago*relevantvars2$slstyr*relevantvars2$slslyr
relevantvars2$slstyr_slslyr_sls2ago_sls3ago[is.na(relevantvars2$slstyr_slslyr_sls2ago_sls3ago)] <- 0

relevantvars2$slstyr_sls2ago <- relevantvars2$slstyr*relevantvars2$sls2ago
relevantvars2$slstyr_sls3ago <- relevantvars2$slstyr*relevantvars2$sls3ago
relevantvars2$slslyr_sls3ago <- relevantvars2$slslyr*relevantvars2$sls3ago
relevantvars2$slslyr_sls2ago_sls3ago <- relevantvars2$sls2ago*relevantvars2$sls3ago*relevantvars2$slslyr

relevantvars2$slstyr_slshist <- relevantvars2$slstyr*relevantvars2$slshist
relevantvars2$slslyr_slshist <- relevantvars2$slslyr*relevantvars2$slshist
relevantvars2$sls2ago_slshist <- relevantvars2$sls2ago*relevantvars2$slshist
relevantvars2$sls3ago_slshist <- relevantvars2$sls3ago*relevantvars2$slshist

relevantvars2$slstyr_greater_slslyr <- (relevantvars2$slstyr > relevantvars2$slslyr)
relevantvars2$slslyr_greater_sls2ago <- (relevantvars2$slslyr > relevantvars2$sls2ago)
relevantvars2$sls2ago_greater_sls3ago <- (relevantvars2$sls2ago > relevantvars2$sls3ago)



```

```{r}
library(dummies)
relevantvars2 <- cbind(relevantvars2,dummy(relevantvars2$consistencycategory))
colnames(relevantvars2)
relevantvars2 <- within(relevantvars2,rm("consistencycategory"))
relevantvars2 <- within(relevantvars2,rm("relevantvars2Ref"))

relevantvars2 <- within(relevantvars2,rm("sprord"))

```


```{r}
head(relevantvars2)
fit3 = lm(log(targdol)~.,data = relevantvars2)
summary(fit3)
```
```{r}
step.forward <- step(fit3, direction = "forward")
step.back <- step(fit3, direction = "backward")
step.coef <- names(coef(step.back))
step.var <- relevantvars2[,(names(relevantvars2) %in% c("targdol",step.coef))]
fit.step <- lm(log(targdol)~., data = step.var)
summary(fit.step)
```

```{r}
library(glmnet)
y = log(relevantvars2$targdol)
x.var <- relevantvars2[2:length(relevantvars2)]
x = model.matrix(~.-1,x.var)

lassofit = glmnet(x,y, alpha = 1, lambda = seq(0,10,0.01))
lassocv = cv.glmnet(x,y,alpha = 1, nfold = 3,lambda = seq(0,10,0.01))
plot(lassocv)
lambdalasso = lassocv$lambda.min
lambdalasso
small.lambda.index <- which(lassocv$lambda == lassocv$lambda.min)
small.lambda.betas <- coef(lassocv$glmnet.fit)[,small.lambda.index]
lasso.coef <- small.lambda.betas[small.lambda.betas != 0]
lasso.coef
```
```{r}
lasso.var <- relevantvars2[,(names(relevantvars2) %in% c("targdol",names(lasso.coef)[-1]))]
fit.lasso <- lm(log(targdol)~., data = lasso.var)
summary(fit.lasso)

```


## Model Diagnostics
```{r}
plot(fit.step, which = 2)
plot(fit.step, which = 1)
plot(fit.step, which = 4)
cooks.distance(fit.step)

plot(fit.lasso, which = 2)
plot(fit.lasso, which = 1)
plot(fit.lasso, which = 4)
vif(fit.lasso)



step.var["48690",]
step.var["72035",]
step.var["72673",]

vif(fit.step)
cor(step.var)
```

# remove outliers
```{r}
rm <- c("48690","72035","72673")
step.var.rm <- step.var[!rownames(step.var) %in% rm,]
fit.step.rm <- lm(log(targdol)~., data = step.var.rm)
summary(fit.step.rm)

plot(fit.step.rm, which = 2)
plot(fit.step.rm, which = 1)
plot(fit.step.rm, which = 4)

```

